### ISSUE TITLE
ESP32-LyraT Noisy sound and more issues

### ISSUE THREAD

**Issue by baesek** [marcel-licence/esp32_midi_sampler#86]
Hi,
I am trying to use the esp32_midi_sampler with the ESP32-LyraT v4.3 Board at the moment and I get a really noisy sound which is covered by a beep tone in the frequency of the BLINK_LED_PIN.
So I commented out the blink process code which removed the repeating beep tone, but what stays is a steady noise floor and really silent sample playback.
I also realized that there is no Sound at all when i comment out pinMode(BLINK_LED_PIN, OUTPUT)
I outputted the value of the BLINK_LED_PIN and got 19 in the serial monitor.

Can you help me to get it work? I got it working with the drum_sampler_project but the midi_sampler is not working yet.

I cannot find where BLINK_LED_PIN is defined i think it is defined in the ml_synth lib

EDIT: I selected the ESP32 Dev Module board in the Arduino IDE. I am not sure if this is correct.
EDIT2: Sample playback works now, only the noise floor problem stays
best,
paul

____
EDIT3:

Now I commented out the pinMode(Blink_LED_PIN, OUTPUT) again with the result of a more silent sample playback but without noise floor. I think I have called the Sampler_NoteOn wrongly.

But I wonder why the playback was much louder with Pin 19 set as an output

**Comment by marcel-licence** [comment]
Hi @baesek,
I could imagine that there might be a pin conflict. I do not have the LyraT board. In some cases there is an amplifier placed on the PCB which can be set on/off. 

Referring to https://espressif-docs.readthedocs-hosted.com/projects/esp-adf/en/latest/design-guide/dev-boards/board-esp32-lyrat-v4.3.html you should replace IO19 by IO22 to get a blinking LED. IO19 should be a headphone detection input.

IO21 might be important to turn on/off the amplifier.

I would like to create a new file for LyraT and place it here: https://github.com/marcel-licence/ML_SynthTools/tree/main/src/boards to have all the pins defined. That could make it easier to select the setting with just one define in the config.h

Hope this helps

**Comment by marcel-licence** [comment]
No update
