### ISSUE TITLE
builtin ADC

### ISSUE THREAD

**Issue by copych** [marcel-licence/esp32_midi_sampler#91]
Hello @marcel-licence , I played for some time with this great app, but as I don't have an i2s mic, I wanted to record from the analog preamped mic MAX9814, as I saw (https://github.com/MhageGH/esp32_SoundRecorder) that it's possible to use an internal ADC for this purpose. But I failed, cause when I add I2S_MODE_ADC_BUILT_IN to the i2s_config.mode, it stops producing any sound via i2s, and I don't understand what should I change, and is it possible to mix all the flags together (cause in the example it only records, not plays back the sound)?
My skills and understanding of i2s are definitely not enough to solve the quest, so can you, please, look at the code?

**Comment by marcel-licence** [comment]
Hello  @copych I am not sure if mixing would be possible. It might be possible to mix ADC and DAC BUILT IN but using an external DAC/ADC might not allow mixing. In this case you should use I2S DIN and DOUT for analog input and output
