### ISSUE TITLE
Audio Kit V2.2 A247 sounds like garbage

### ISSUE THREAD

**Issue by quiknick** [marcel-licence/esp32_midi_sampler#95]
@marcel-licence Not sure how much you can help in this regard, but cannot get this Audio Kit V2.2 A247 to sound like your video. This thing just sounds terrible and no matter trying to switch to input rather than mic, mic stays engaged and has all of these electronic artifacts. Wonder if these new ES8388 is the issue. Not sure what to do here.

**Comment by marcel-licence** [comment]
Did you find out the reason?
