### ISSUE TITLE
What pins for connecting SD Card Module to ESP32 Devkit V1 DOIT?

### ISSUE THREAD

**Issue by satriamahen** [marcel-licence/esp32_midi_sampler#97]
I got everything working as I intended, just missing the SD Card functionality. Because I don't know where to connect the SD Card module to the ESP32 Devkit V1 DOIT. Can anybody help me? Thanks in advance!

**Comment by satriamahen** [comment]
![image](https://github.com/marcel-licence/esp32_midi_sampler/assets/49549410/386ed8d6-4a9a-4931-b7cb-9621fd4016f6)
Will this connection work?

**Comment by marcel-licence** [comment]
Using SPI you would be flexible with the used pins. It can be mapped by the ESP32. If you need a fast connection you should use SD_MMC. It can use 1 or 4 data lines. In case you use SD_MMC pull-up resistors may be required.

Did you run some example code to test the sd-card?
